### PR TITLE
Android - Fixes https://github.com/apache/cordova-plugin-network-information#110

### LINKED ISSUE #93: NFC scan fire onConnect event on Android device
# Bug Report
NFC scan fire onConnect event
## Problem
When I scan an NFC Tag using ionic recommended nfc plugin "chariotsolutions/phonegap-nfc". Then the onConnect event is fired. And it says that "wifi" ist connected:

Connection: {UNKNOWN: "unknown", ETHERNET: "ethernet", WIFI: "wifi", CELL_2G: "2g", CELL_3G: "3g", …

### What is expected to happen?
The onConnect event should not be fired when you scan an NFC tag.

### What does actually happen?
The onConnect event is fired when you scan an NFC tag.

## Information

It happens in an ionic app.

### Environment, Platform, Device

Tested on Android 5.01 and 9 devices

### Version information

Installed versions:
"@ionic-native/network": "^5.11.0",
"cordova-plugin-network-information": "2.0.2",
@ionic-native/nfc": "^5.3.0",
 "phonegap-nfc": "^1.0.3",
"@ionic/angular": "^4.9.1",
 "cordova-android": "^7.1.4",

## Checklist

- [x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

### LINKED ISSUE #101: OnConnect event fired when USB device connected on Android. Using latest version.
# Bug Report
OnConnect event fired when USB device connected on Android. It's on Ionic 5 app. I have tested on two real devices.

When downgrading to 2.0.1 everything works fine. Is there another fix?

### Version information
Ionic CLI                     : 5.4.15 (/usr/lib/node_modules/ionic)
Ionic Framework               : @ionic/angular 4.11.5
@angular-devkit/build-angular : 0.801.3
@angular-devkit/schematics    : 8.1.3
@angular/cli                  : 8.1.3
@ionic/angular-toolkit        : 2.1.1
Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0
cordova-plugin-network-information: 2.0.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

### PR DESCRIPTION
**Pull request by PieterVanPoyer**
### Platforms affected

Android

### Motivation and Context

Fixes #101 
Fixes https://github.com/apache/cordova-plugin-network-information/issues/110
Fixes #93

### Description

The JSONObject of Android does not have an equals implementation. So the equals between previous networkinfo and new networkinfo state always returned false.
I've explicitly tested all properties of the JSONObject for equality.

After a review I noticed that the "extraInfo' value of the JSONObject was not used and needed at all. So I did simplify the plugin to keep the state in a String member. So now the equality is done on a simple String object.

### Testing

I did test it on an Android Nexus 5X Emulator and on my Samsung .

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change => Was not necessary
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary. => Was not necessary.

I didn't prefix the commit, but I did prefix the PR.

This replaces https://github.com/apache/cordova-plugin-network-information/pull/111 . The original was started from the master branche. This PR is started from a bugfix-branche.

### CODE REVIEW

File: src/android/NetworkManager.java [hunk 1]
```diff
@@ -230,9 +230,44 @@ private void updateConnectionInfo(NetworkInfo info) {
...
+        }
+
+        if (valueInJSONObjectDiffersForKey(thisInfo , lastInfo, "type")) {
+            return true;
+        }
+
+        return valueInJSONObjectDiffersForKey(thisInfo , lastInfo, "extraInfo");
+    }
+
+    private boolean valueInJSONObjectDiffersForKey(JSONObject firstObject, JSONObject secondObject, String key) {
```
Comment (PieterVanPoyer) [inline src/android/NetworkManager.java:255]: Maybe we should just get rid of the JSONObject in this plugin.
We could refactor it to a seperate (VO-class) with two fields: 'type' and 'extraInfo'.
This class could have a correct equals and hashcode function.

This could make the try - catch constructions with JSONException obsolete on a lof of places.

**Comment by breautek** [comment]
Comments on the original still applies: https://github.com/apache/cordova-plugin-network-information/pull/111#issuecomment-640073128

With the important note of:

> This looks good to me. While this is fixing a bug, it is changing behaviour (which is to stop event firing on resume, if there was no change in state), which is a behaviour that some people may be dependent on. Because of this, I think we need to treat this as a breaking change.

File: src/android/NetworkManager.java (hunk 1 above)
Comment (breautek) [reply src/android/NetworkManager.java:255]: As long as this doesn't affect the `PluginResult` responses, then I don't have any objection. But do you think it's necessary to be as a part of a bugfix PR, or should that change be a separate refactor PR?

Comment (PieterVanPoyer) [reply src/android/NetworkManager.java:255]: I did take a second look to the code.
The pluginResult is just the "type" of network.

So this made my reflect a little bit about the "extraInfo" state.

```
JSONObject connectionInfo = new JSONObject();
 try {
       connectionInfo.put("type", type);
       connectionInfo.put("extraInfo", extraInfo);
  } catch (JSONException e) {
      LOG.d(LOG_TAG, e.getLocalizedMessage());
 }
```

If I read the code the "extraInfo" is not used at all, it is stored in the JsonObject, but is not used or read anywhere else in the NetworkManager class.

This remark is just about the boyscout rule ( Leave your code better than you found it ).
Maybe a next developer is happy that someone left it cleaner. 
So my suggestions are: 
- remove the JSONObject, just use a String for type as state.
- remove the "extraInfo" state.

I leave it over to your decision if it should be a seperate PR, or not.
But I am willing to make these changes in this or another PR. (It's milestone 3, so there is time?)

Comment (PieterVanPoyer) [reply src/android/NetworkManager.java]: Done.
I am not 100% with the naming of the method: getTypeOfNetworkFallbackToTypeNoneIfNotConnected , but it is okay.

My tests on the emulator were successfull. I am planning on doing some tests on my mobile phone.

There is still more unused code in the plugin in my opinion, but that's for another iteration.

Comment (PieterVanPoyer) [reply src/android/NetworkManager.java]: Tests on the mobile phone were successfull. Seems to work.

**Comment by breautek** [comment]
Do let me know when it's ready for second review.

**Comment by PieterVanPoyer** [comment]
Ready for 2nd review.

**Comment by PieterVanPoyer** [comment]
Hey @timbru31  or @erisu 

I do not like to disturb you guys, but does anyone have time to review this PR?
I am always available to discuss this PR.

Kind regards
Pieter

File: src/android/NetworkManager.java [hunk 2]
```diff
@@ -167,16 +161,11 @@ public void onReceive(Context context, Intent intent) {
                         updateConnectionInfo(sockMan.getActiveNetworkInfo());
                     }
 
-                    String connectionType = null;
-                    if(NetworkManager.this.lastInfo == null) {
+                    String connectionType;
+                    if(NetworkManager.this.lastTypeOfNetwork == null) {
```
Comment (timbru31) [inline src/android/NetworkManager.java:165]:
```suggestion
                    if (NetworkManager.this.lastTypeOfNetwork == null) {
```

File: src/android/NetworkManager.java [hunk 3]
```diff
@@ -218,30 +207,25 @@ private void unregisterReceiver() {
     private void updateConnectionInfo(NetworkInfo info) {
         // send update to javascript "navigator.network.connection"
         // Jellybean sends its own info
-        JSONObject thisInfo = this.getConnectionInfo(info);
-        if(!thisInfo.equals(lastInfo))
+        String currentNetworkType = this.getTypeOfNetworkFallbackToTypeNoneIfNotConnected(info);
+        if(currentNetworkType.equals(this.lastTypeOfNetwork))
         {
```
Comment (timbru31) [inline src/android/NetworkManager.java:212]:
```suggestion
        if (currentNetworkType.equals(this.lastTypeOfNetwork)) {
```

File: src/android/NetworkManager.java [hunk 4]
```diff
@@ -218,30 +207,25 @@ private void unregisterReceiver() {
...
-            String connectionType = "";
-            try {
-                connectionType = thisInfo.get("type").toString();
-            } catch (JSONException e) {
-                LOG.d(LOG_TAG, e.getLocalizedMessage());
-            }
-
-            sendUpdate(connectionType);
-            lastInfo = thisInfo;
+            LOG.d(LOG_TAG, "Networkinfo state didn't change, there is no event propagated to the javascript side.");
```
Comment (timbru31) [inline src/android/NetworkManager.java:213]:
```suggestion
            LOG.d(LOG_TAG, "Networkinfo state didn't change, there is no event propagated to the JavaScript side.");
```

File: src/android/NetworkManager.java [hunk 5]
```diff
@@ -289,46 +263,41 @@ private void sendUpdate(String type) {
...
-            if (type.equals(WIFI)) {
-                return TYPE_WIFI;
-            }
-            else if (type.toLowerCase().equals(TYPE_ETHERNET) || type.toLowerCase().startsWith(TYPE_ETHERNET_SHORT)) {
-                return TYPE_ETHERNET;
-            }
-            else if (type.equals(MOBILE) || type.equals(CELLULAR)) {
-                type = info.getSubtypeName().toLowerCase(Locale.US);
-                if (type.equals(GSM) ||
+        LOG.d(LOG_TAG, "toLower : " + type.toLowerCase());
```
Comment (timbru31) [inline src/android/NetworkManager.java:268]: The `toLowerCase()` seems redundant.

File: src/android/NetworkManager.java [hunk 6]
```diff
@@ -289,46 +263,41 @@ private void sendUpdate(String type) {
      * @return the type of mobile network we are on
      */
     private String getType(NetworkInfo info) {
-        if (info != null) {
-            String type = info.getTypeName().toLowerCase(Locale.US);
+        String type = info.getTypeName().toLowerCase(Locale.US);
```
Comment (timbru31) [inline src/android/NetworkManager.java:266]: Can `getTypeName()` ever return null? We've either need to guard this or reverse all `.equals` checks.

File: src/android/NetworkManager.java [hunk 7]
```diff
@@ -289,46 +262,37 @@ private void sendUpdate(String type) {
...
-            else if (type.toLowerCase().equals(TYPE_ETHERNET) || type.toLowerCase().startsWith(TYPE_ETHERNET_SHORT)) {
-                return TYPE_ETHERNET;
-            }
-            else if (type.equals(MOBILE) || type.equals(CELLULAR)) {
-                type = info.getSubtypeName().toLowerCase(Locale.US);
-                if (type.equals(GSM) ||
+        String type = info.getTypeName().toLowerCase(Locale.US);
+
+        LOG.d(LOG_TAG, "toLower : " + type);
+        LOG.d(LOG_TAG, "wifi : " + WIFI);
```
Comment (PieterVanPoyer) [inline src/android/NetworkManager.java:268]: Why do we even log the WIFI time after time. It just the constant wifi.
I think this can just be removed.

File: src/android/NetworkManager.java (hunk 2 above)
Comment (PieterVanPoyer) [reply src/android/NetworkManager.java]: done

File: src/android/NetworkManager.java (hunk 3 above)
Comment (PieterVanPoyer) [reply src/android/NetworkManager.java]: done. In the other parts of the NetworkManager class, there are also strange indentations, but I rather leave them untouched.

File: src/android/NetworkManager.java (hunk 7 above)
Comment (breautek) [reply src/android/NetworkManager.java:268]: Agreed.

File: src/android/NetworkManager.java (hunk 6 above)
Comment (PieterVanPoyer) [reply src/android/NetworkManager.java:265]: Seems like it never returns null.

File: src/android/NetworkManager.java (hunk 5 above)
Comment (PieterVanPoyer) [reply src/android/NetworkManager.java]: I'vre removed the lowercase.

File: src/android/NetworkManager.java [hunk 8]
```diff
@@ -289,46 +262,36 @@ private void sendUpdate(String type) {
...
-            }
-            else if (type.equals(MOBILE) || type.equals(CELLULAR)) {
-                type = info.getSubtypeName().toLowerCase(Locale.US);
-                if (type.equals(GSM) ||
+        String type = info.getTypeName().toLowerCase(Locale.US);
+
+        LOG.d(LOG_TAG, "toLower : " + type);
+        if (type.equals(WIFI)) {
+            return TYPE_WIFI;
+        } else if (type.toLowerCase().equals(TYPE_ETHERNET) || type.toLowerCase().startsWith(TYPE_ETHERNET_SHORT)) {
```
Comment (PieterVanPoyer) [inline src/android/NetworkManager.java:270]: toLowerCase() is still present on this line.  But I rather leave this one like it is.
I don't like to change something that I am unable to test easy.

**Comment by PieterVanPoyer** [comment]
> It would also be nice if you could bring all the else/else if statement of `getType` to the same line as the bracket.

I am not entirely sure about your remark. But I did improve it a little bit.

**Comment by PieterVanPoyer** [comment]
Hey @timbru31 or @erisu

I do not like to disturb you guys, but does anyone have time to review/approve this PR?
I am sometimes available to discuss this PR.

Kind regards
Pieter

**Comment by breautek** [comment]
It looks like all the requested changes from @timbru31 have been made.

I'm going to say a last call for reviews. If there are no responses by Tuesday, July 7th, I'll merge this in.

**Comment by davidpadych** [comment]
Hi,
when will the new version be released? merged with this PR .. thank you

**Comment by breautek** [comment]
> Hi,
> when will the new version be released? merged with this PR .. thank you

Can't really provide any ETAs on releases.

**Comment by breautek** [comment]
There was no responses, so I'm merging in.

You can also ignore the TotalPave review, that was me on the wrong account.

Thank you @PieterVanPoyer for your time and effort.

**Comment by PieterVanPoyer** [comment]
Hey

I did enjoy contributing a little.
Your enthusiasm is infectious.

I got a few questions
- Can we speed up the release process in some way? If yes, how?

- Working on the plugin was not that smooth for me, I did copy paste the Java code from a test project to the plugin project. Is there a better workflow, for developing or contributing to plugins?

- Is it possible to open an issue or a milestone, or something to discuss the future requirements of the plugin (v4). Something like a whitepaper. I did made some suggestions in this comment https://github.com/apache/cordova-plugin-network-information/issues/110#issuecomment-639588835 . You did already do some suggestions in next comment: https://github.com/apache/cordova-plugin-network-information/issues/91#issuecomment-580906459

Kind regards
Pieter
